spring.application.name=iqms-backend
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/iqms}

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174,https://interactive-question-management-she-gamma.vercel.app
app.auth.secret=replace-with-strong-secret
app.auth.expiration-seconds=604800
